seed: 2022
debug: false
first_batch: 1
all_batch: 15
srate: 200
windowLength: 14
windowStep: 4
#trial_start: 240
#trial_end: 241

trainer_name: CrossVal
model_name: MACTN
train_bs: 32
val_bs: 32
epochs: 300
lr: 0.0005
l2norm: 0.1
T_0: 10
min_lr: 1.0e-7

dropout_rate: 0.5
accum_iter: 2
verbose_step: 1
#flood_b: 0.0

n_fold: 45
num_classes: 3
device: 0
ckpt_dir: './ckpt'
ckpt_name: 'SEED_Emotion'
scheduler_patience: 5
scheduler_factor: 0.2
earlystop_patience: 10
min_delta: 0

low_cut: 1
high_cut: 45
re_srate: 100
bp_low: 1
bp_high: 45
bs_low: 48
bs_high: 52
rerefence_type: 'bipolar_SEED'
channels: 60
use_de_feature: false
freq_bands: [[1, 3], [4, 7], [8, 13], [14, 30], [30, 45]]
is_save_model: true

input_shape: [60, 1400]